/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Edwin
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        ingresarMenuItem = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();
        comprarMenu = new javax.swing.JMenu();
        cataloCompraMenuItem = new javax.swing.JMenuItem();
        persoBiciMenuItem = new javax.swing.JMenuItem();
        alquilarMenu = new javax.swing.JMenu();
        cataloAlquilerMenuItem = new javax.swing.JMenuItem();
        copyMenuItem1 = new javax.swing.JMenuItem();
        mantenerMenu = new javax.swing.JMenu();
        cutMenuItem2 = new javax.swing.JMenuItem();
        copyMenuItem2 = new javax.swing.JMenuItem();
        pasteMenuItem2 = new javax.swing.JMenuItem();
        deleteMenuItem2 = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        archivoMenu.setMnemonic('a');
        archivoMenu.setText("Archivo");

        ingresarMenuItem.setMnemonic('i');
        ingresarMenuItem.setText("Ingresar");
        archivoMenu.add(ingresarMenuItem);

        salirMenuItem.setMnemonic('s');
        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        archivoMenu.add(salirMenuItem);

        menuBar.add(archivoMenu);

        comprarMenu.setMnemonic('c');
        comprarMenu.setText("Comprar");

        cataloCompraMenuItem.setMnemonic('t');
        cataloCompraMenuItem.setText("Catálogo de biclietas");
        comprarMenu.add(cataloCompraMenuItem);

        persoBiciMenuItem.setMnemonic('p');
        persoBiciMenuItem.setText("Personalizar bicicleta");
        comprarMenu.add(persoBiciMenuItem);

        menuBar.add(comprarMenu);

        alquilarMenu.setMnemonic('l');
        alquilarMenu.setText("Alquilar");

        cataloAlquilerMenuItem.setMnemonic('b');
        cataloAlquilerMenuItem.setText("Catálogo de bicicletas");
        alquilarMenu.add(cataloAlquilerMenuItem);

        copyMenuItem1.setMnemonic('f');
        copyMenuItem1.setText("Facturar");
        alquilarMenu.add(copyMenuItem1);

        menuBar.add(alquilarMenu);

        mantenerMenu.setMnemonic('m');
        mantenerMenu.setText("Mantenimiento");

        cutMenuItem2.setMnemonic('t');
        cutMenuItem2.setText("Cut");
        mantenerMenu.add(cutMenuItem2);

        copyMenuItem2.setMnemonic('y');
        copyMenuItem2.setText("Copy");
        mantenerMenu.add(copyMenuItem2);

        pasteMenuItem2.setMnemonic('p');
        pasteMenuItem2.setText("Paste");
        mantenerMenu.add(pasteMenuItem2);

        deleteMenuItem2.setMnemonic('d');
        deleteMenuItem2.setText("Delete");
        mantenerMenu.add(deleteMenuItem2);

        menuBar.add(mantenerMenu);

        ayudaMenu.setMnemonic('u');
        ayudaMenu.setText("Ayuda");

        aboutMenuItem.setMnemonic('d');
        aboutMenuItem.setText("Acerca de...");
        ayudaMenu.add(aboutMenuItem);

        menuBar.add(ayudaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu alquilarMenu;
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JMenuItem cataloAlquilerMenuItem;
    private javax.swing.JMenuItem cataloCompraMenuItem;
    private javax.swing.JMenu comprarMenu;
    private javax.swing.JMenuItem copyMenuItem1;
    private javax.swing.JMenuItem copyMenuItem2;
    private javax.swing.JMenuItem cutMenuItem2;
    private javax.swing.JMenuItem deleteMenuItem2;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem ingresarMenuItem;
    private javax.swing.JMenu mantenerMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem2;
    private javax.swing.JMenuItem persoBiciMenuItem;
    private javax.swing.JMenuItem salirMenuItem;
    // End of variables declaration//GEN-END:variables

}
